model_params:
  name: 'AE'
  latent_vecs: 128 # for hybrid sampling
  residual: True
  latent_size: 4
  enc_depth: 6 #number of convolutional layers in the encoder
  dec_depth: 6
  channels: 16
  pool_every: 2
  gaussian_init: 'xavier' #other option: 'normal'
  loss_type: "BCE"


opt_params:
  LR: 0.0005
  weight_decay: 0.0

trainer_params:
  max_steps: 80000
  val_check_interval: 10
  progress_bar_refresh_rate: 10
  log_every_n_steps: 10


vis_params:
  plot_every: 20



eval_params:
  FID: False