model_params:
  name: 'AE'
  latent_vecs: 128 # for hybrid sampling
  residual: True
  latent_size: 4
  enc_depth: 3 #number of convolutional layers in the encoder
  dec_depth: 3
  pool_every: 1
  channels: 4
  gaussian_init: 'xavier' #other option: 'normal'
  loss_type: "BCE"

opt_params:
  LR: 0.0005
  weight_decay: 0.0

trainer_params:
  max_steps: 80000
  val_check_interval: 10
  progress_bar_refresh_rate: 10
  log_every_n_steps: 10

logging_params:
  save_dir: "./logs/"

vis_params:
  plot_every: 5