model_params:
  name: 'AE'
  latent_vecs: 128 # for hybrid sampling
  residual: True
  latent_size: 6
  enc_depth: 6 #number of convolutional layers in the encoder
  dec_depth: 6
  num_pools: 3
  unit_dim: 1
  channels: 32
  loss_type: "MSE"

eval_params:
  name: "scoring"
  FID: False
  latent_responses: True

