eval_params:
  FID: false
  name: scoring
model_params:
  channels: 32
  dec_depth: 12
  enc_depth: 12
  latent_size: 12
  latent_vecs: 128
  name: AE
  num_pools: 3
  random_seed: 17
  residual: true
  unit_dim: 1
