model_params:
  latent_size: 32
  enc_depth: 16 #number of convolutional layers in the encoder
  dec_depth: 16
  num_pools: 7
  unit_dim: 1
  loss_type: "MSE"
  channels: 100

eval_params:
  name: "scoring"
  FID: True

trainer_params:
  max_steps: 200000