model_params:
  name: 'VecESAE'
  latent_vecs: 128 # for hybrid sampling
  latent_size: 10
  depth: 5 #number of linear layers in the encoder and decoder
  unit_dim: 1
  # --------- parameters related to MMD kernel setting ----------
  MMD_kernel: "RBF" #or IMQ or cat
  #"strict": False
  #"hierarchy": False
  lamda: 2.0
  full: False
  act: 'leaky_relu'

logging_params:
  manual_seed: 1265
  save_dir: "./logs/"
  score_every: 20 # number of validations

trainer_params:
  val_check_interval: 500 #check validation every 200 steps
  max_steps: 20000