model_params:
  name: 'VecESAE'
  latent_vecs: 128 # for hybrid sampling
  latent_size: 10
  depth: 8 #number of linear layers in the encoder and decoder
  unit_dim: 1
  # --------- parameters related to MMD kernel setting ----------
  MMD_kernel: "RBF" #or IMQ or cat
  #"strict": False
  #"hierarchy": False
  lamda: 2.0
