model_params:
  name: 'ESAE'
  latent_vecs: 128 # for hybrid sampling
  residual: True
  latent_size: 10
  enc_depth: 6 #number of convolutional layers in the encoder
  dec_depth: 6
  pool_every: 2
  unit_dim: 2
  norm: 'group'
  channels: 64
  # --------- parameters related to MMD kernel setting ----------
  MMD_kernel: "RBF" #or IMQ or cat
  #"strict": False
  #"hierarchy": False
  lamda: 2.0

vis_params:
  plot_every: 1

