model_params:
  name: 'ESAE'
  latent_vecs: 128 # for hybrid sampling
  residual: True
  latent_size: 12
  enc_depth: 12 #number of convolutional layers in the encoder
  dec_depth: 6
  pool_every: 2
  unit_dim: 2
  channels: 32
  # --------- parameters related to MMD kernel setting ----------
  MMD_kernel: "IMQ" #or IMQ or cat
  #"strict": False
  #"hierarchy": False
  lamda: 4.0

vis_params:
  plot_every: 5


logging_params:
  score_every: 100
#  save_dir: "./logs/"


