model_params:
  name: 'BetaVAE'
  beta: 6.0
  residual: True
  latent_size: 12
  enc_depth: 6 #number of convolutional layers in the encoder
  dec_depth: 6
  pool_every: 2
  channels: 64
  dittadi: False
  gaussian_init: 'xavier' #other option: 'normal'

opt_params:
  KL_decay: 1.0
  beta_schedule: 'cyclic'
