model_params:
  name: 'XCVAE'
  beta: 4.0
  latent_size: 6
  enc_depth: 3 #number of convolutional layers in the encoder
  dec_depth: 3
  num_pools: 3
  unit_dim: 2
  norm: 'batch'
  channels: 32
  gaussian_init: 'xavier' #other option: 'normal'
  # invariance regularisation parameters
  lamda: 2.0
  num_samples: 100
  num_interventions: 20

vis_params:
  plot_every: 10

logging_params:
  score_every: 1000
  save_dir: "./logs/"

