model_params:
  name: 'XCVAE'
  beta: 4.0
  latent_size: 12
  enc_depth: 12 #number of convolutional layers in the encoder
  dec_depth: 12
  num_pools: 3
  unit_dim: 1
  channels: 32
  gaussian_init: 'xavier' #other option: 'normal'
  # invariance regularisation parameters
  sparsity_lamda: 2.0
  invariance_lamda: 1.0
  num_samples: 10
  num_interventions: 10
  sparsity: True


opt_params:
  KL_decay: 1.0
  beta_schedule: 'linear'
  inv_lamda_schedule: 'linear'

eval_params:
  name: "scoring"
  FID: True
  latent_responses: True
  mode: 'X'

vis_params:
  plot_every: 5 # hugher frequency for slower training