model_params:
  name: 'XCWAE'
  latent_vecs: 128 # for hybrid sampling
  residual: True
  latent_size: 12
  enc_depth: 12 #number of convolutional layers in the encoder
  dec_depth: 12
  num_pools: 3
  unit_dim: 1
  channels: 32
  MMD_kernel: 'IMQ'
  prior_type: 'Gaussian'
  prior_scale: 1.0
  # regularisation parameters
  MMD_lamda: 100.0
  sparsity_lamda: 2.0
  sparsity: False
  # parameters for the causal latent block
  parents_with_grad: True
  gumbel: True


opt_params:
  MMD_lamda_schedule: 'linear'