model_params:
  name: 'CausalVAE'
  latent_size: 4
  enc_depth: 6 #number of convolutional layers in the encoder
  dec_depth: 6
  channels: 16
  pool_every: 2
  unit_dim: 1
  gaussian_init: 'xavier' #other option: 'normal'
  loss_type: "BCE"
  convolutional: True


opt_params:
  LR: 0.0001
  weight_decay: 0.0
  alpha: 0.3
  beta: 1.0
  gamma: 1.0

trainer_params:
  max_steps: 80000