model_params:
  act: elu
  convolutional: false
  gaussian_init: xavier
  latent_size: 4
  loss_type: MSE
  name: CausalVAE
  pool_every: 2
  random_seed: 17
  unit_dim: 4
opt_params:
  LR: 0.0001
  alpha: 0.3
  beta: 1.0
  gamma: 1.0
  weight_decay: 0.0
trainer_params:
  max_steps: 80000
