model_params:
  name: 'CausalVAE'

opt_params:
  LR: 0.0001
  weight_decay: 0.0
  alpha: 0.3
  beta: 1.0
  gamma: 1.0
  pretraining: -1 # number of pre-training epochs

trainer_params:
  max_steps: 80000
  val_check_interval: 10
  progress_bar_refresh_rate: 10
  log_every_n_steps: 10


eval_params:
  FID: False