eval_params:
  FID: true
  latent_responses: true
  mode: X
  name: scoring
model_params:
  channels: 32
  dec_depth: 12
  enc_depth: 12
  gumbel: true
  latent_size: 12
  latent_vecs: 128
  name: XSAE
  num_pools: 3
  parents_with_grad: true
  random_seed: 17
  residual: true
  sparsity: false
  sparsity_lamda: 2.0
  unit_dim: 1
opt_params:
  weight_decay: 0.0
