model_params:
  name: 'XSAE'
  latent_vecs: 128 # for hybrid sampling
  residual: True
  latent_size: 12
  enc_depth: 12 #number of convolutional layers in the encoder
  dec_depth: 12
  num_pools: 3
  unit_dim: 1
  channels: 32
  # sparsity regularisation parameters
  sparsity_lamda: 2.0
  sparsity: False
  # parameters for the causal latent block
  parents_with_grad: True
  gumbel: True



eval_params:
  name: "scoring"
  FID: True
  latent_responses: True
  mode: 'X'


opt_params:
  weight_decay: 0.0