model_params:
  latent_size: 32
  enc_depth: 16 #number of convolutional layers in the encoder
  dec_depth: 16
  num_pools: 7
  unit_dim: 1
  loss_type: "MSE"
  channels: 100
  num_samples: 3
  num_interventions: 1
  invariance_lamda: 4.0
  xunit_dim: 4


trainer_params:
  max_steps: 200000