model_params:
  name: 'BaseSAE'
  latent_vecs: 128 # for hybrid sampling
  residual: True
  latent_size: 12
  enc_depth: 12 #number of convolutional layers in the encoder
  dec_depth: 6
  pool_every: 2
  unit_dim: 2
  channels: 32