model_params:
  name: 'BaseSAE'
  latent_vecs: 128 # for hybrid sampling
  residual: True
  latent_size: 6
  enc_depth: 12 #number of convolutional layers in the encoder
  dec_depth: 6
  num_pools: 3
  unit_dim: 1
  channels: 32


eval_params:
  name: "scoring"
  FID: False
  latent_responses: True