model_params:
  name: 'RSAE'
  latent_vecs: 128 # for hybrid sampling
  residual: True
  latent_size: 12
  enc_depth: 12 #number of convolutional layers in the encoder
  dec_depth: 12
  num_pools: 3
  unit_dim: 1
  channels: 32
  # --------- parameters related to MMD kernel setting ----------
  MMD_kernel: "RBF" #or IMQ or cat
  #"strict": False
  #"hierarchy": False
  lamda: 2.0



logging_params:
  score_every: 1000
  save_dir: "./logs/"