model_params:
  name: 'RSAE'
  latent_vecs: 128 # for hybrid sampling
  residual: True
  latent_size: 12
  enc_depth: 12 #number of convolutional layers in the encoder
  dec_depth: 6
  pool_every: 2
  unit_dim: 2
  channels: 32
  # --------- parameters related to MMD kernel setting ----------
  MMD_kernel: "RBF" #or IMQ or cat
  #"strict": False
  #"hierarchy": False
  lamda: 4.0
