eval_params:
  FID: false
model_params:
  channels: 16
  dec_depth: 6
  enc_depth: 6
  gaussian_init: xavier
  gumbel: true
  latent_size: 4
  latent_vecs: 128
  loss_type: BCE
  name: XAE
  parents_with_grad: true
  pool_every: 2
  random_seed: 13
  residual: true
  sparsity: false
  sparsity_lamda: 2.0
opt_params:
  LR: 0.0005
  weight_decay: 0.0
trainer_params:
  log_every_n_steps: 10
  max_steps: 80000
  progress_bar_refresh_rate: 10
  val_check_interval: 10
vis_params:
  plot_every: 20
