model_params:
  name: 'BaseSAE'
  latent_size: 12
  enc_depth: 12 #number of convolutional layers in the encoder
  dec_depth: 12
  pool_every: 3
  unit_dim: 4
  upsampling_factor: 2
  latent_vecs: 128 # for hybrid sampling

opt_params:
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  auto_epochs: -1

data_params:
  dataset_name: RFD
  batch_size: 144 # Better to have a square number
  test_batch_size: 144
  heldout: False
  real: False
  subset: False #limit number of samples to 100'000 (to avoid memory errors)

trainer_params:
  gpus: 0
  max_epochs: 100

tuner_params:
  num_samples: 1
  cpus: 1

logging_params:
  save_dir: "logs/"
  name: "BaseSAE"
  manual_seed: 1265
  version: v5
  plot_every: 5

