model_params:
  name: 'SAE'
  beta: 4.0
  latent_dim: 32
  channels_list: [32, 32, 64]
  filter_size: 4

opt_params:
  LR: 0.0001
  weight_decay: 0.0
  scheduler_gamma: 0.95


data_params:
  dataset_name: cifar10
  batch_size: 144 # Better to have a square number
  test_batch_size: 144
  train_split: 0.7

trainer_params:
  gpus: 1
  max_epochs: 50

logging_params:
  save_dir: "logs/"
  name: "BetaVAE"
  manual_seed: 1265
  version: v9
  plot_every: 5

