model_params:
  name: 'SAE'
  latent_dim: 32
  channels_list_enc: [32, 32, 64, 64]
  channels_list_dec: [64, 32, 64, 32]
  filter_size: 4
  stride: 2
  unit_dim: 8
  upsampling_factor: 2
  latent_vecs: 128 # for hybrid sampling

opt_params:
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  auto_epochs: 0


data_params:
  dataset_name: MNIST
  batch_size: 144 # Better to have a square number
  test_batch_size: 144
  train_split: 0.7

trainer_params:
  gpus: 1
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  name: "SAE"
  manual_seed: 1265
  version: v2
  plot_every: 5

