model_params:
  name: 'null'

opt_params:
  LR: 0.0001
  weight_decay: 0.0
  scheduler_gamma: 0.95

data_params:
  dataset_name: 'null'

trainer_params:
  gpus: 1
  max_epochs: 300

logging_params:
  save_dir: "logs/"
  manual_seed: 1265
  version: 'null'
  score_every: 20


vis_params:
  save_dir: "vis/"
  plot_every: 10
  num_animations: 5
  num_frames: 5
  fpd: 10
  num_points_irs: 10000


