model_params:
  name: 'null'
  norm: 'batch'
  act: 'mish'
  loss_type: "BCE"

opt_params:
  LR: 0.0001
  weight_decay: 0.0
  scheduler_gamma: 0.95

data_params:
  dataset_name: null
  batch_size: 128 # Better to have a square number
  test_batch_size: 128
  reload_dataloaders_every_epoch: False
  add_noise: False
  FID_scoring: True

trainer_params:
  val_check_interval: 200 #check validation every 200 steps
  fast_dev_run: False # must be used only for debugging purposes
  max_steps: 100000
  num_sanity_val_steps: 2
  benchmark: False
  deterministic: True #might make the system slower

logging_params:
  save_dir: "/cluster/scratch/glanzillo/logs/"
  manual_seed: 1265
  version: 'null'
  score_every: 20 # number of validations
  log_every: 100

vis_params:
  save_dir: "vis/"
  plot_every: 10
  num_animations: 5
  num_frames: 5
  fpd: 10
  num_points_irs: 10000

eval_params:
  name: "scoring"
  FID: True
  disentanglement: True
  orthogonality: True



