model_params:
  name: 'null'
  norm: 'batch'
  act: 'mish'
  loss_type: "MSE"
  random_seed: 11

opt_params:
  LR: 0.0001
  weight_decay: 0.0
  scheduler_type: 'step' # 'exp' or 'step' or 'null'
  scheduler_gamma: 0.5
  schedulers_step: 30
  betas: [0.9, 0.999]

data_params:
  dataset_name: null
  batch_size: 128 # Better to have a square number
  test_batch_size: 128
  reload_dataloaders_every_epoch: False
  add_noise: False
  FID_scoring: True
  pin_memory: True

trainer_params:
  val_check_interval: 200 #check validation every 200 steps
  fast_dev_run: False # must be used only for debugging purposes
  max_steps: 100000
  num_sanity_val_steps: 2
  benchmark: True
  #precision: 16 - DOES'NT WORK, EVERYTHING EXPLODES
  progress_bar_refresh_rate: 50
  log_every_n_steps: 50
  auto_select_gpus: True #select all the gpus available
  min_epochs: 1
  accelerator: null #'ddp'
  gpus: 1


logging_params:
  save_dir: "/cluster/scratch/glanzillo/logs"
  manual_seed: 1265
  version: 'null'
  score_every: 20 # number of validations
  log_every: 100

vis_params:
  save_dir: "vis/"
  plot_every: 10
  num_animations: 5
  num_frames: 5
  fpd: 10
  num_points_irs: 10000
  figsize: [12,18]

eval_params:
  name: "scoring"
  FID: True
  disentanglement: True
  orthogonality: True
  latent_responses: True
  invariances: True
  # invariances parameters ----
  mode: 'X'
  hard: True
  num_interventions: 50
  num_samples: 100
  num_batches: 10
  n_iters: 10000
  num_FID_steps: 10




