model_params:
  name: 'VAE'
  beta: 4.0
  latent_size: 12
  enc_depth: 12 #number of convolutional layers in the encoder
  dec_depth: 12
  pool_every: 3
  residual: True

opt_params:
  LR: 0.0001
  weight_decay: 0.0
  scheduler_gamma: 0.95
  KL_decay: 0.9999


data_params:
  dataset_name: 3DShapes
  batch_size: 500 # Better to have a square number
  test_batch_size: 500

trainer_params:
  gpus: 1
  max_epochs: 300

logging_params:
  save_dir: "logs/"
  name: "BetaVAE"
  manual_seed: 1265
  version: VAE12_shapes3d
  score_every: 20


vis_params:
  save_dir: "vis/"
  plot_every: 10
  num_animations: 5
  num_frames: 5
  fpd: 10
  num_points_irs: 10000


