model_params:
  name: 'VAE'
  beta: 10.0
  latent_dim: 10
  channels_list: [32, 64, 128, 256]

opt_params:
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.95


data_params:
  dataset_name: cifar10
  batch_size: 144 # Better to have a square number
  test_batch_size: 400
  train_split: 0.7

trainer_params:
  gpus: 1
  max_epochs: 50

logging_params:
  save_dir: "logs/"
  name: "BetaVAE_B"
  manual_seed: 1265
