eval_params:
  FID: true
  latent_responses: true
  mode: X
  name: scoring
model_params:
  beta: 4.0
  channels: 32
  dec_depth: 12
  enc_depth: 12
  gaussian_init: xavier
  gumbel: true
  latent_size: 12
  loss_type: BCE
  name: XVAE
  num_pools: 3
  parents_with_grad: true
  random_seed: 17
  sparsity: false
  sparsity_lamda: 2.0
  unit_dim: 1
opt_params:
  KL_decay: 1.0
  beta_schedule: linear
  weight_decay: 0.0
