model_params:
  name: 'XVAE'
  latent_size: 12
  enc_depth: 12 #number of convolutional layers in the encoder
  dec_depth: 12
  num_pools: 3
  unit_dim: 1
  channels: 32
  gaussian_init: 'xavier' #other option: 'normal'
  #regularisation parameters
  beta: 4.0
  sparsity_lamda: 2.0
  sparsity: True


opt_params:
  KL_decay: 1.0
  beta_schedule: 'linear'

eval_params:
  name: "scoring"
  FID: True
  latent_responses: True
  mode: 'X'
